### ISSUE TITLE
Windows & matlab 2014a

### ISSUE THREAD

**Issue by flip111** [bmsherman/haskell-matlab#4]
The `bin\glnxa64\` folder is not available on my system. How to proceed?

Error message: `* Missing C libraries: mx, mat, eng`

**Comment by bmsherman** [comment]
For the MATLAB Compiler Runtime on Windows, the command might look like
```
cabal install --extra-include-dirs="C:\Program Files\MATLAB\MATLAB Compiler Runtime\v83\extern\include" --extra-lib-dirs="C:\Program Files\MATLAB\MATLAB Compiler Runtime\v83\bin\win64"
```
. For MATLAB 2014a, I imagine it looks like this
```
cabal install --extra-include-dirs="C:\Program Files\MATLAB\R2014a\extern\include" --extra-lib-dirs="C:\Program Files\MATLAB\R2014a\bin\win64"
```
, but I can't say for sure. Basically, your library files should be located in `bin\win64` for Windows, rather than `bin/glnxa64`, which is specific to Linux.
