### ISSUE TITLE
Bump cabal dependency

### ISSUE THREAD

**Issue by imalsogreg** [bmsherman/haskell-matlab#5]
Is it possible to support Cabal-1.22._, Cabal-1.23._?

**Comment by bmsherman** [comment]
I imagine that it is! If you are able to successfully install with the latest version of Cabal, just let me know, and I'd be happy to update the Cabal dependency bound here and on Hackage. I just tried to do this on my own machine today, but ran into another difficulty that prevented me from testing this (something related to GMP on Mac with GHC 7.10).

**Comment by bmsherman** [comment]
We updated version bounds for dependencies here: https://github.com/bmsherman/haskell-matlab/commit/4c57a51ccdb86a4747fb42b41e4bf5f4df1e023f.
