### ISSUE TITLE
matrix ?

### ISSUE THREAD

**Issue by enoshima** [bmsherman/haskell-matlab#6]
Hello,
This seems to be very useful! I understand I can save a 1-dimension vector using createColVector or something like this. How about matrix?
Kazuhiro

**Comment by dylex** [comment]
You can create an arbitrary array using `createMXArray` and a sequence of `mxArraySetOffset` to fill in the values.  You can also use the `IMX` interface for construction: `withIMXData (listIMX [2,3] [1,2,3,4,5,6]) $ \matrix -> ...`.  (It would be nice to have more instances in `Auto` for `Vector` and friends nawadays, too...)
