### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by Elektroingenieur** [bmsherman/haskell-matlab#7]
Hi, could you please update its dependencies to support ghc version 8.4.4, thanks in advance.

**Comment by bmsherman** [comment]
I'm not set up on my machine to be able to test this at the moment, unfortunately.

I tried updating the bounds in https://github.com/bmsherman/haskell-matlab/tree/updated_bounds. Could you try that and let me know if it works? If so, I can merge it into the master branch and also push an update to Hackage.
